<?php

namespace SymfonyCollection\DotpayBundle\Repository;

/**
 * ChannelCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
