<?php

namespace SymfonyCollection\DotpayBundle\Repository;

/**
 * ErrorCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ErrorCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
