<?php

namespace SymfonyCollection\DotpayBundle\Repository;

/**
 * OperationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
