<?php

namespace SymfonyCollection\DotpayBundle\Repository;

/**
 * OperationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
