<?php

namespace SymfonyCollection\DotpayBundle\Repository;

/**
 * PaymentRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
