<?php

namespace SymfonyBundles\DotpayBundle\Repository;

/**
 * PaymentStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
